### PR TITLE
Provide a way to identify the lowest defined investment size

### PR DESCRIPTION
**Pull request by munckymagik**
... without hard coding things.

Needed for https://github.com/moneyadviceservice/rad_consumer/pull/238

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
:+1:

**Comment by rnalexander** [comment]
:+1: :shipit:

**Comment by urfolomeus** [comment]
:doffs cap: :+1:

**Comment by munckymagik** [comment]
Thanks folks

**Pull request merged**
