### PR TITLE
Use Faker to produce unique names.

### PR DESCRIPTION
**Pull request by neoeno**
Sometimes everyone being named Ben Lovell can cause false positives.
It's hard to tell whether the Ben Lovell you have is the one you want.

### CODE REVIEW

**Comment by darokel** [comment]
Haha. :+1:

**Comment by rnalexander** [comment]
:+1:  DESTROY ALL LOVELLS.

**Comment by tomas-stefano** [comment]
LOL :+1:

**Comment by benlovell** [comment]
Noooooooooooooooooooooooooooooooo!

**Comment by dougdroper** [comment]
too late

**Pull request merged**
