### PR TITLE
[DEV APPROVED] Only include offices that have been geocoded

### PR DESCRIPTION
**Pull request by munckymagik**
How about having absolutely no nils to worry about on directory side, under any circumstances?

### CODE REVIEW

**Comment by mconnell** [comment]
:+1: I like it

**Comment by urfolomeus** [comment]
:+1:  moi aussi

**Comment by JiggyPete** [comment]
:+1:

**Comment by benbarnett** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
:+1:

**Pull request merged**
