### PR TITLE
[DEV APPROVED] Upgrade rails version (4.2.10)

### PR DESCRIPTION
**Pull request by osharpe**
TP 8702 https://moneyadviceservice.tpondemand.com/entity/8702

This PR is upgrade the Rails version to 4.2.10

### CODE REVIEW

**Comment by willhall88** [comment]
getting the same rspec errors as Travis. give me a shout if you want to pair to fix

**Comment by osharpe** [comment]
Thanks Will. I wasn't getting those failures before, but it looks like the upgraded active_model_serializers (0.10.7) the root = false is not required.

**Comment by willhall88** [comment]
cool. tests all passing now 👍 
Happy with this PR to be merged.
There are a lot of deprecation warnings in the tests, mainly down to factoryGirl, so another PR should be followed to address this. I'm happy to pick this up though once your work is done, if you like.

**Comment by osharpe** [comment]
Ye we have this across quite a lot of Repo's. Would be good if we can follow up with new PR to resolve this. Thanks @willhall88

**Comment by pmcostello** [comment]
👍

**Pull request merged**
