### PR TITLE
adds CSV renderer for Adviser objs

### PR DESCRIPTION
**Pull request by Tr4pSt3R**
Supports this ticket: https://github.com/moneyadviceservice/rad/pull/406

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/mas-rad_core/163)

### CODE REVIEW

**Comment by willhall88** [comment]
any tests to support this code?

**Comment by Tr4pSt3R** [comment]
@willhall88 there's a test here: https://github.com/moneyadviceservice/rad/blob/8070-advisors_list_export/spec/features/admin/export_advisers_list_spec.rb#L100

With that being said maybe I should add a unit test for this method. I shall do so.

**Comment by tomas-stefano** [comment]
Second thought on that. Since this is only on the admin I would create a simple Ruby class on rad admin instead of moving to the model.

Just a fake example:

```ruby
class AdvisersListCsv
   def initialize(advisers)
      @advisers = advisers
   end

def self.to_csv(_ = {})
     CSV.generate do |csv|
        csv << ['Ref. Number', 'Name', 'Firm']
 
        @advisers.each do |adviser|
          csv << [adviser.reference_number, adviser.name, adviser.firm.registered_name]
        end
     end
   end
end
```

And then on controller you can pass this object to respond_with using the Responders feature.

I would close this issue and moving the code to the rad admin.

**Comment by Tr4pSt3R** [comment]
Moving the implementation from here to the RAD repo.

**Pull request closed without merging**
