### PR TITLE
Add #all_firms association to Principal (plus minor tidy-ups)

### PR DESCRIPTION
**Pull request by munckymagik**
This association is needed for the recently-updated firms lists on the new self-service dashboard in RAD.

### CODE REVIEW

**Comment by munckymagik** [comment]
Going to pushing some changes to this.

**Comment by munckymagik** [comment]
After the rename it's usage looks like this: https://github.com/moneyadviceservice/rad/commit/6ba4b21f57b8d6b622767dd74a95cb59f2f21050

@neoeno @urfolomeus @mconnell @JiggyPete ^^ Any better?

**Comment by neoeno** [comment]
good name I think :+1:

**Comment by tomas-stefano** [comment]
:+1:

**Comment by urfolomeus** [comment]
Yeah, much prefer this. Good times :) :+1:

**Pull request merged**
