### PR TITLE
[DEV APPROVED] Remove GeocodeAdviserJob

### PR DESCRIPTION
**Pull request by munckymagik**
Geocoding is no longer done in the background for Advisers (or anything else).

(If you need some context have a look at #125, this is a clean up task that falls out of that work)

### CODE REVIEW

**Comment by mconnell** [comment]
:+1:

**Comment by urfolomeus** [comment]
:+1:

**Comment by benbarnett** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
brill! :+1:

**Pull request merged**
